// Central icon map: Phosphor names (used by the legacy UI) → Lucide components.
// Astryx <Icon icon={...} /> accepts a Lucide component directly, so these are
// the canonical icons used across the app during and after the migration.
import {
  Bell,
  ChevronRight,
  Check,
  Circle,
  CircleCheck,
  ClipboardList,
  ForkKnife,
  MapPin,
  PawPrint,
  Pencil,
  Pill,
  Plus,
  CirclePlus,
  Syringe,
  Toilet,
  Droplet,
  X,
  Camera,
  Trash2,
  Download,
  Upload,
  RefreshCw,
  Phone,
  Dog,
  Minus,
  House,
  Stethoscope,
  User,
  LayoutDashboard,
  LayoutGrid,
  ChartColumnBig,
  Play,
  ChevronDown,
  ChevronLeft,
  Lock,
  Eye,
  EyeOff,
  Sun,
  Cloud,
  CloudRain,
  Wind,
  Snowflake,
  Thermometer,
  CloudFog,
  CloudLightning,
  EllipsisVertical,
  Copy,
  Link,
  QrCode,
  UsersRound,
  FileText,
  ShieldCheck,
  IdCard,
  Paperclip,
} from "lucide-react";

export const Icons = {
  bell: Bell,
  caretRight: ChevronRight,
  caretLeft: ChevronLeft,
  check: Check,
  circle: Circle,
  checkCircle: CircleCheck,
  clipboardText: ClipboardList,
  forkKnife: ForkKnife,
  mapPin: MapPin,
  pawPrint: PawPrint,
  pencilSimple: Pencil,
  pill: Pill,
  plus: Plus,
  plusCircle: CirclePlus,
  syringe: Syringe,
  toilet: Toilet,
  droplet: Droplet,
  x: X,
  camera: Camera,
  trash: Trash2,
  download: Download,
  upload: Upload,
  refresh: RefreshCw,
  phone: Phone,
  dog: Dog,
  minus: Minus,
  house: House,
  stethoscope: Stethoscope,
  user: User,
  layoutDashboard: LayoutDashboard,
  layoutGrid: LayoutGrid,
  chartColumn: ChartColumnBig,
  play: Play,
  chevronDown: ChevronDown,
  lock: Lock,
  eye: Eye,
  eyeOff: EyeOff,
  sun: Sun,
  cloud: Cloud,
  cloudRain: CloudRain,
  wind: Wind,
  snowflake: Snowflake,
  thermometer: Thermometer,
  cloudFog: CloudFog,
  cloudLightning: CloudLightning,
  moreVertical: EllipsisVertical,
  copy: Copy,
  link: Link,
  qrCode: QrCode,
  users: UsersRound,
  fileText: FileText,
  shieldCheck: ShieldCheck,
  idCard: IdCard,
  paperclip: Paperclip,
} as const;

export type AppIconName = keyof typeof Icons;
