// Central icon map: Phosphor names (used by the legacy UI) → Lucide components.
// Astryx <Icon icon={...} /> accepts a Lucide component directly, so these are
// the canonical icons used across the app during and after the migration.
import {
  Bell,
  ChevronRight,
  Check,
  CircleCheck,
  ClipboardList,
  ForkKnife,
  MapPin,
  PawPrint,
  Pencil,
  Pill,
  Plus,
  Syringe,
  Toilet,
  Droplet,
  X,
  Camera,
  Trash2,
  Download,
  Upload,
  RefreshCw,
  Phone,
  Dog,
  Minus,
  House,
  Stethoscope,
  User,
  ChevronDown,
} from "lucide-react";

export const Icons = {
  bell: Bell,
  caretRight: ChevronRight,
  check: Check,
  checkCircle: CircleCheck,
  clipboardText: ClipboardList,
  forkKnife: ForkKnife,
  mapPin: MapPin,
  pawPrint: PawPrint,
  pencilSimple: Pencil,
  pill: Pill,
  plus: Plus,
  syringe: Syringe,
  toilet: Toilet,
  droplet: Droplet,
  x: X,
  camera: Camera,
  trash: Trash2,
  download: Download,
  upload: Upload,
  refresh: RefreshCw,
  phone: Phone,
  dog: Dog,
  minus: Minus,
  house: House,
  stethoscope: Stethoscope,
  user: User,
  chevronDown: ChevronDown,
} as const;

export type AppIconName = keyof typeof Icons;
