/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/ui/lib/theme.ts
 * Command: astryx theme build src/ui/lib/theme.ts
 * Generated: 2026-09-29T11:00:20.197Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const pawpalTheme: DefinedTheme;
